version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mybatis-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mybatis_db
      MYSQL_USER: mybatis_user
      MYSQL_PASSWORD: mybatis_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

volumes:
  mysql_data: